# config.yaml

window:
  title: "Калькулятор конечной арифметики Z8"
  geometry: "300x450"
  resizable_width: false
  resizable_height: false
  background_color: "#2e2e2e"

colors:
  background: "#2e2e2e"
  button: "#4a4a4a"
  operator: "#ff9500"
  clear: "#d9d9d9"
  text: "#ffffff"
  display_background: "#1c1c1c"
  active_button: "#6e6e6e"
  active_operator: "#ffb84d"
  active_clear: "#e6e6e6"

fonts:
  name: "Segoe UI"
  size_display: 24
  size_button: 16

buttons:
  - text: 'C'
    style: 'Clear.TButton'
    grid: [0, 0, 1, 1] # row, column, rowspan, columnspan
  - text: ''
    style: 'TButton'
    grid: [0, 1, 1, 1]
  - text: ''
    style: 'TButton'
    grid: [0, 2, 1, 1]
  - text: '/'
    style: 'Operator.TButton'
    grid: [0, 3, 1, 1]
  - text: 'h'
    style: 'TButton'
    grid: [1, 0, 1, 1]
  - text: 'g'
    style: 'TButton'
    grid: [1, 1, 1, 1]
  - text: 'f'
    style: 'TButton'
    grid: [1, 2, 1, 1]
  - text: '*'
    style: 'Operator.TButton'
    grid: [1, 3, 1, 1]
  - text: 'e'
    style: 'TButton'
    grid: [2, 0, 1, 1]
  - text: 'd'
    style: 'TButton'
    grid: [2, 1, 1, 1]
  - text: 'c'
    style: 'TButton'
    grid: [2, 2, 1, 1]
  - text: '-'
    style: 'Operator.TButton'
    grid: [2, 3, 1, 1]
  - text: 'b'
    style: 'TButton'
    grid: [3, 0, 1, 1]
  - text: 'a'
    style: 'TButton'
    grid: [3, 1, 1, 1]
  - text: '='
    style: 'Operator.TButton'
    grid: [3, 2, 1, 1]
    colspan: 2 # Дополнительное поле для columnspan
  - text: '+'
    style: 'Operator.TButton'
    grid: [3, 3, 1, 1]